---
title: "R Notebook"
output: html_notebook
---

```{r}
library(RPostgreSQL)

home_location <- Sys.getenv("HOME")
credentials_location <- paste0(home_location,"/credentials.R")
source(credentials_location)

db_connect <- dbConnect(drv = PostgreSQL(), user = postgresql_username, password = postgresql_password, dbname = "omni_employees", host = "localhost")

rm(postgresql_username, postgresql_password)
```

All employees who work in the ‘Human Resources’ department
```{sql connection=db_connect}
SELECT * 
FROM employees
WHERE department = 'Human Resources'
```

The first name, last name, and country of the employees who work in the ‘Legal’ department
```{sql connection=db_connect}
SELECT
  first_name,
  last_name,
  country
FROM employees
WHERE department = 'Legal'
```

Count of the number of employees based in Portugal
```{sql connection=db_connect}
SELECT
  COUNT(id) AS number_of_employees_portugal
  FROM employees
  WHERE country = 'Portugal'
```

Count number of employees based in either Portugal or Spain
```{sql connection=db_connect}
SELECT
  COUNT(id) AS number_of_employees_portugal_spain
  FROM employees
  WHERE country = 'Portugal' OR country = 'Spain'
```

Count of the number of pay_details records lacking a local_account_no
```{sql connection=db_connect}
SELECT
  COUNT(id) AS pay_details_lacking_local_account_no
  FROM pay_details
  WHERE local_account_no IS NULL
```

```{sql connection=db_connect}
SELECT *
 FROM pay_details
```


Are there any pay_details record lacking both a local_account_no and iban number?
```{sql connection=db_connect}
SELECT
  COUNT(id) AS pay_details_lacking_local_account_no_and_iban
  FROM pay_details
  WHERE local_iban IS NULLaccount_no IS NULL AND 
```

List of employees first names and last names ordered alphabetically by their last name (put nulls last).
```{sql connection=db_connect}
SELECT
  first_name,
  last_name,
  CONCAT(first_name, ' ', last_name)
FROM employees
ORDER by last_name ASC NULLS LAST
```

List of employees first names, last names and countries, ordered alphabetically first by their country and second by their last name (put any nulls last)
```{sql connection=db_connect}
SELECT
  first_name,
  last_name,
  country
FROM employees
ORDER by country ASC NULLS LAST AND last_name ASC NULLS LAST
```

Top ten highest paid employees in the corporation.
```{sql connection=db_connect}
SELECT *
  FROM employees
  ORDER by salary DESC NULLS LAST
  LIMIT 10
```

First name, last name and salary of the lowest paid of the employees in Hungary
```{sql connection=db_connect}
SELECT 
  first_name,
  last_name,
  country
  FROM employees
  WHERE country = 'Hungary'
  ORDER by salary ASC NULLS LAST
  LIMIT 1
```

How many employees have a first name beginning with ‘F’?
```{sql connection=db_connect}
SELECT *
  FROM employees
  WHERE first_name LIKE 'F%'
```

Find all the details of any employees with a ‘yahoo’ e-mail address?
```{sql connection=db_connect}
SELECT *
  FROM employees
  WHERE email LIKE '%yahoo%'
```

Count number of pension enrolled employees not based in either France or Germany
```{sql connection=db_connect}
SELECT
  COUNT(id) AS pension_enrolled_employ_not_based_Fr_or_Ger
  FROM employees
  WHERE (country != 'Germany' AND country != 'France') AND (pension_enrol IS TRUE)
```

Breakdown the numbers of employees enrolled, not enrolled and whose enrollment status is unknown in the corporation pension scheme.
```{sql connection=db_connect}


```

What is the maximum salary among employees in the Engineering department who work 1.0 full-time equivalent hours?
```{sql connection=db_connect}


```

A count by department of the employees who started work with the corporation in 2003
```{sql connection=db_connect}


```


```{sql connection=db_connect}


```
