---
title: "R Notebook"
output: html_notebook
---

```{r}
library(CodeClanData)
```
```{r}
library(readr)
```

1.1 Read file
```{r}
state_income_data <- read_csv("data/state_income_data.csv")
state_income_data
```

1.2 Columns

```{r}
state_income_data <- read_csv("data/state_income_data.csv",
  col_names = c(
    "column_name1",
    "column_name1",
    "column_name3",
    "column_name4"
  )
)
```

1.3 Cars
```{r}
cars_data <- read_csv("data/cars.csv")
cars_data 
```

```{r}
cars_data <- read_csv(("data/cars.csv"),
cols(X1 = col_character(),
  `mpg` = col_double(),
  'cyl` = col_double(),
  `disp` = col_double(),
  `hp` = col_double(),
  'vs" = col_logical().
))
cars_data
```

1.4 Scotland file
```{r}
scotland_data <- read_tsv("data/scotland.txt")
scotland_data
```

1.5 Read text into a one element character vecto


1.6
```{r}
steam_200k_sample <- read_csv("data/steam-200k-sample.csv")
steam_200k_sample
```

1.7 
```{r}
historic_eu_payments <- read_tsv("data/historic_eu_payments.tsv")
historic_eu_payments
```

1.8 Read lines of text 


1.9 JSON file
```{r}
json_file <- read_file("http://makemeanalyst.com/wp-content/uploads/2017/06/sample_json.txt")
json_file
```

```{r}
install.packages("jsonlite")
prettify(json_file)
json_file
```





